// ATTENZIONE: questo file deve essere rigenerato in locale con:
// flutterfire configure --project=pet-care-9790d
// Le chiavi presenti nel repo sono placeholder e vanno sovrascritte in locale.
//
// ISTRUZIONI PER L'OWNER:
// 1. Installa FlutterFire CLI: dart pub global activate flutterfire_cli
// 2. Rigenera il file: flutterfire configure --project=pet-care-9790d
// 3. Seleziona piattaforme: Android, Web, iOS
// 4. Conferma sovrascrittura di questo file
//
// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYmHD9bdyek_sg-DBAJH25eWRGOuWIF6k',
    appId: '1:72431103725:web:4ee4fb4a04f1ec39e326e4',
    messagingSenderId: '72431103725',
    projectId: 'pet-care-9790d',
    authDomain: 'pet-care-9790d.firebaseapp.com',
    storageBucket: 'pet-care-9790d.appspot.com',
  );

  // Android configuration - Extracted from google-services.json
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKAKCjJb2_utnE7GVKYoRJL54TkKRzxKs',
    appId: '1:72431103725:android:a2bbea591780a9d7e326e4',
    messagingSenderId: '72431103725',
    projectId: 'pet-care-9790d',
    storageBucket: 'pet-care-9790d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAzxhOpTqgrbhyEcWsAlMNN6k8FtkcSkU',
    appId: '1:72431103725:ios:b8e4fb4a04f1ec39e326e4',
    messagingSenderId: '72431103725',
    projectId: 'pet-care-9790d',
    storageBucket: 'pet-care-9790d.appspot.com',
    iosBundleId: 'it.mypetcare.myPetCare',
  );
}
